before_install:
  - sudo apt-get install -y libudev-dev
language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
before_script:
  - rustup component add rustfmt-preview
  - which rustfmt
script:
  - cargo test --verbose --workspace
  - cargo test --release --verbose --workspace
  - cd ublox
  - cargo build --examples
  - cargo doc
  - cargo build --features "serial" --examples
  - cargo doc --features "serial"
