[package]
name = "ublox_derive"
version = "0.0.1"
authors = ["Lane Kolbly <lane@rscheme.org>"]
edition = "2018"
publish = false

[dependencies]
quote = "1.0"
syn = { version = "1.0.14", features = ["extra-traits", "parsing", "full"] }
proc-macro2 = { version = "1.0", features = ["span-locations"] }
log = "0.4"

[dev-dependencies]
which = { version = "3.0", default-features = false }