[package]
name = "ublox_derive"
version = "0.0.0"
authors = ["Lane Kolbly <lane@rscheme.org>"]
edition = "2018"
publish = false

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "1.0.14", features = ["extra-traits"] }
proc-macro-error = "0.4.8"
