[package]
name = "ublox_derive"
version = "0.0.1"
authors = ["Lane Kolbly <lane@rscheme.org>"]
edition = "2018"
publish = false

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "1.0.14", features = ["extra-traits", "full"] }

[dev-dependencies]
which = { version = "3.0", default-features = false }
proc-macro2 = { version = "1.0", features = ["span-locations"] }